apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzELr//////////wEaDIyQjGQ18HtMLA/A5yK7AY9ZI+8lZQ3G8/WgSf76jawRvIZTjxMkVHJHT9vIAdi7CvmxJNevBaKuIpsLaDOWxhkLuqaTlh2vodzD9c1rpQMB+1r38/2eDLhun6v8mB3Be94XoUVRiYNMU3SCK38YB84grJ8cRijWioDtdM30AH7xm/tx+40JK5dvOgqUonFCwqF3arwwMmkHPGZBhULYQNizs4Bda3+nO29NshUkd219L8wpjenoim4qzeAheeF6t0ZmFVTNLDE9Zn4oj5WFmwYyLd8PEOsX238PHiqfZXMy9d2n/VMOQcshv1LrdMpMGR74FimezYDGJ54xOIcVrg==
 #aws_access_key_id: QUtJQVhRQkZCVk01Q0pVSVRKRkQ=
 #aws_secret_access_key: RGhuTWUxaEpHYllPS3ArbklUS1VRMFZyV05zcnpreExxbWdrem5vbg==
 #aws_session_token: FwoGZXIvYXdzELb//////////wEaDJB7BY57FuOdl2TH2yK7AUQ+F2QNtMDn+uh8e9yDLAXCvD7m+yeDLiFTwU3JKOKrarWBpyvHbBOpvdmktRPsO3sEj40vcsZF9P7S4XMlpTNi7QyzXa+VXR+44U+2y3hpl6GzwwGlwaIjRa8rCGpx5TaWFJd8z+9Fjh03mIyh5XbaKFjuD65Rt6clMMRaLQObTqhrAk3aXDpk9wBDOqgINx7CCD5vxL23VZ13HxJZ+TJPhK9qtw2sGGqc6EwIZIythRfACVgTIQpQjw8oq6aEmwYyLaVDuKBVv5jZV1DB0gb6MQ8fNdN2OsvLjkeLLknUMVB6o9wdLX/aaoocPtiLIg==
